#!/usr/bin/env python3
# Copyright 2026 Lyle Mills.
# SPDX-License-Identifier: MIT
"""Generate Wave Scan's lossless block-packed second-difference wave bank."""

from __future__ import annotations

import argparse
from pathlib import Path


NUM_WAVES = 256
SOURCE_WAVE_SIZE = 129
WAVE_SIZE = 128
START_MARKER = "// BEGIN GENERATED WAVE SCAN BANK"
END_MARKER = "// END GENERATED WAVE SCAN BANK"
BLOCK_SIZE = 16


def residuals(wave: bytes) -> list[int]:
    result: list[int] = []
    previous_sample = wave[0]
    previous_difference = 0
    for sample in wave[1:]:
        difference = sample - previous_sample
        if difference > 127:
            difference -= 256
        elif difference < -128:
            difference += 256
        result.append(difference - previous_difference)
        previous_sample = sample
        previous_difference = difference
    return result


def signed_width(values: list[int]) -> int:
    for width in range(1, 17):
        if all(-(1 << (width - 1)) <= value < (1 << (width - 1)) for value in values):
            return width
    raise ValueError("residual does not fit in 16 signed bits")


def encode_block(values: list[int]) -> bytes:
    width = signed_width(values)
    output = bytearray()
    output.append(width)
    byte = 0
    bit_index = 0

    def write_bit(bit: int) -> None:
        nonlocal byte, bit_index
        byte |= bit << bit_index
        bit_index += 1
        if bit_index == 8:
            output.append(byte)
            byte = 0
            bit_index = 0

    mask = (1 << width) - 1
    for signed_value in values:
        value = signed_value & mask
        for value_bit in range(width):
            write_bit((value >> value_bit) & 1)

    if bit_index:
        output.append(byte)
    return bytes(output)


def format_array(c_type: str, name: str, values: list[int], width: int) -> str:
    lines = [f"const {c_type} {name}[{len(values)}] = {{"]
    for offset in range(0, len(values), width):
        chunk = values[offset : offset + width]
        lines.append("  " + ", ".join(str(value) for value in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def generate(source: Path) -> str:
    data = source.read_bytes()
    expected_size = NUM_WAVES * SOURCE_WAVE_SIZE
    if len(data) != expected_size:
        raise ValueError(f"{source} is {len(data)} bytes; expected {expected_size}")

    first_samples: list[int] = []
    offsets = [0]
    encoded = bytearray()

    for wave_index in range(NUM_WAVES):
        start = wave_index * SOURCE_WAVE_SIZE
        source_wave = data[start : start + SOURCE_WAVE_SIZE]
        if source_wave[-1] != source_wave[0]:
            raise ValueError(f"wave {wave_index} has a non-matching wrap guard")
        wave = source_wave[:WAVE_SIZE]
        values = residuals(wave)
        first_samples.append(wave[0])
        for block_start in range(0, len(values), BLOCK_SIZE):
            encoded.extend(encode_block(values[block_start : block_start + BLOCK_SIZE]))
        offsets.append(len(encoded))

    arrays = [
        format_array("uint16_t", "kWaveOffsets", offsets, 12),
        format_array("uint8_t", "kWaveFirstSamples", first_samples, 16),
        format_array("uint8_t", "kWaveResiduals", list(encoded), 16),
    ]
    storage = (
        len(encoded)
        + len(first_samples)
        + 2 * len(offsets)
    )
    header = f"""{START_MARKER}
// Generated by plaits/resources/compress_wave_scan.py from waves.bin.
// Each wave stores sample 0 verbatim, then 127 signed first/second
// differences in blocks of {BLOCK_SIZE}. Each block starts with its fixed signed
// bit width and is byte-aligned; values and bits are LSB-first. Fixed-width
// extraction avoids the Rice decoder's data-dependent unary loop.
// {storage:,} B total ({len(encoded):,} B payload).
"""
    return header + "\n\n".join(arrays) + f"\n{END_MARKER}"


def replace_generated_block(target_text: str, generated: str) -> str:
    if START_MARKER in target_text:
        start = target_text.index(START_MARKER)
        end = target_text.index(END_MARKER, start) + len(END_MARKER)
        return target_text[:start] + generated + target_text[end:]

    legacy_start = target_text.index("// Braids' wave bank, vendored.")
    legacy_end = target_text.index("// wt_map:", legacy_start)
    return target_text[:legacy_start] + generated + "\n\n" + target_text[legacy_end:]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="fail if the generated block is stale"
    )
    args = parser.parse_args()

    resources = Path(__file__).resolve().parent
    source = resources / "waves.bin"
    target = resources.parent / "dsp" / "engine2" / "wave_scan_engine.cc"
    old_text = target.read_text(encoding="utf-8")
    new_text = replace_generated_block(old_text, generate(source))
    if args.check:
        if new_text != old_text:
            print(f"error: generated Wave Scan bank is stale: {target}")
            return 1
        return 0
    target.write_text(new_text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
