#!/usr/bin/env python3
# Copyright 2026 Lyle Mills.
# SPDX-License-Identifier: MIT
"""Generate Wave Scan's lossless second-difference Rice-coded wave bank."""

from __future__ import annotations

import argparse
from pathlib import Path


NUM_WAVES = 256
SOURCE_WAVE_SIZE = 129
WAVE_SIZE = 128
START_MARKER = "// BEGIN GENERATED WAVE SCAN BANK"
END_MARKER = "// END GENERATED WAVE SCAN BANK"
DECODE_PADDING = 2


def zigzag(value: int) -> int:
    return value << 1 if value >= 0 else ((-value << 1) - 1)


def residuals(wave: bytes) -> list[int]:
    result = [wave[1] - wave[0]]
    for index in range(2, WAVE_SIZE):
        result.append(wave[index] - 2 * wave[index - 1] + wave[index - 2])
    return result


def choose_rice_parameter(values: list[int]) -> int:
    encoded = [zigzag(value) for value in values]
    return min(
        range(8),
        key=lambda parameter: sum(
            (value >> parameter) + 1 + parameter for value in encoded
        ),
    )


def encode_rice(values: list[int], parameter: int) -> bytes:
    output = bytearray()
    byte = 0
    bit_index = 0

    def write_bit(bit: int) -> None:
        nonlocal byte, bit_index
        byte |= bit << bit_index
        bit_index += 1
        if bit_index == 8:
            output.append(byte)
            byte = 0
            bit_index = 0

    for signed_value in values:
        value = zigzag(signed_value)
        for _ in range(value >> parameter):
            write_bit(0)
        write_bit(1)
        for remainder_bit in range(parameter):
            write_bit((value >> remainder_bit) & 1)

    if bit_index:
        output.append(byte)
    return bytes(output)


def format_array(c_type: str, name: str, values: list[int], width: int) -> str:
    lines = [f"const {c_type} {name}[{len(values)}] = {{"]
    for offset in range(0, len(values), width):
        chunk = values[offset : offset + width]
        lines.append("  " + ", ".join(str(value) for value in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def generate(source: Path) -> str:
    data = source.read_bytes()
    expected_size = NUM_WAVES * SOURCE_WAVE_SIZE
    if len(data) != expected_size:
        raise ValueError(f"{source} is {len(data)} bytes; expected {expected_size}")

    first_samples: list[int] = []
    parameters: list[int] = []
    offsets = [0]
    encoded = bytearray()

    for wave_index in range(NUM_WAVES):
        start = wave_index * SOURCE_WAVE_SIZE
        source_wave = data[start : start + SOURCE_WAVE_SIZE]
        if source_wave[-1] != source_wave[0]:
            raise ValueError(f"wave {wave_index} has a non-matching wrap guard")
        wave = source_wave[:WAVE_SIZE]
        values = residuals(wave)
        parameter = choose_rice_parameter(values)
        packet = encode_rice(values, parameter)
        first_samples.append(wave[0])
        parameters.append(parameter)
        encoded.extend(packet)
        offsets.append(len(encoded))

    padded_residuals = encoded + bytes(DECODE_PADDING)
    arrays = [
        format_array("uint16_t", "kWaveOffsets", offsets, 12),
        format_array("uint8_t", "kWaveFirstSamples", first_samples, 16),
        format_array("uint8_t", "kWaveRiceParameters", parameters, 24),
        format_array("uint8_t", "kWaveResiduals", list(padded_residuals), 16),
    ]
    storage = (
        len(padded_residuals)
        + len(first_samples)
        + len(parameters)
        + 2 * len(offsets)
    )
    header = f"""{START_MARKER}
// Generated by plaits/resources/compress_wave_scan.py from waves.bin.
// Each wave stores sample 0 verbatim, then 127 signed first/second
// differences as ZigZag-coded Rice values. Packets and bits are LSB-first;
// each packet is byte-aligned. Two trailing bytes make 16-bit decoder refills
// in the final packet safe. {storage:,} B total ({len(encoded):,} B payload).
"""
    return header + "\n\n".join(arrays) + f"\n{END_MARKER}"


def replace_generated_block(target_text: str, generated: str) -> str:
    if START_MARKER in target_text:
        start = target_text.index(START_MARKER)
        end = target_text.index(END_MARKER, start) + len(END_MARKER)
        return target_text[:start] + generated + target_text[end:]

    legacy_start = target_text.index("// Braids' wave bank, vendored.")
    legacy_end = target_text.index("// wt_map:", legacy_start)
    return target_text[:legacy_start] + generated + "\n\n" + target_text[legacy_end:]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="fail if the generated block is stale"
    )
    args = parser.parse_args()

    resources = Path(__file__).resolve().parent
    source = resources / "waves.bin"
    target = resources.parent / "dsp" / "engine2" / "wave_scan_engine.cc"
    old_text = target.read_text(encoding="utf-8")
    new_text = replace_generated_block(old_text, generate(source))
    if args.check:
        if new_text != old_text:
            print(f"error: generated Wave Scan bank is stale: {target}")
            return 1
        return 0
    target.write_text(new_text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
