// Copyright 2026 Lyle Mills.
// SPDX-License-Identifier: MIT
//
// Host preview renderer for Natural Speech word banks.
//
// The Customize Speech editor has to let you hear a bank BEFORE committing to
// a firmware build, and for this engine that is not a nicety: WORLD analysis
// is where words go wrong (a fricative stored as voiced turns /s/ into /z/),
// and no amount of listening to the source TTS would reveal it.
//
// So this renders through the SHIPPED engine rather than reimplementing it.
// The bank arrives as the very header the firmware compiles -- generated by
// natural_speech_banks.render_natural_speech_config and force-included here --
// which is what makes the preview and the built firmware the same synthesis by
// construction rather than by discipline.
//
//   render_natural_speech_preview <output-dir> [seconds-per-word]
//
// Writes 48 kHz mono <bank>-<word>-{natural,flat}.wav, matching the LPC
// editor's two prosody modes, plus concatenated bank-{natural,flat}.wav.

#include <cstdio>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <new>
#include <string>
#include <vector>

#include "plaits/dsp/engine2/natural_speech_engine.h"
#include "stmlib/dsp/dsp.h"
#include "stmlib/utils/random.h"

namespace bank = plaits::natural_speech_recipe;

namespace {

const size_t kBlock = 24;
const float kSampleRate = 48000.0f;

// Voice's registered gain for this engine, from the catalog's postProcessing
// block. It is NOT readable from a standalone engine instance, so it has to be
// mirrored here -- without it raw output peaks past full scale and the preview
// clips where the hardware would not. Positive, so no limiter (a limiter is
// only used where the registered gain is negative).
const float kOutGain = 0.8f;

// Mirrors the firmware's per-voice arena.
char g_ram_block[16 * 1024];

void WriteWav(const std::string& path, const std::vector<float>& samples) {
  std::vector<int16_t> pcm(samples.size());
  for (size_t i = 0; i < samples.size(); ++i) {
    float x = samples[i];
    if (x > 1.0f) x = 1.0f;
    if (x < -1.0f) x = -1.0f;
    pcm[i] = static_cast<int16_t>(x * 32767.0f);
  }
  const uint32_t data_bytes = static_cast<uint32_t>(pcm.size() * 2);
  const uint32_t rate = static_cast<uint32_t>(kSampleRate);
  FILE* f = fopen(path.c_str(), "wb");
  if (!f) {
    fprintf(stderr, "cannot open %s\n", path.c_str());
    exit(1);
  }
  const uint32_t riff = 36 + data_bytes;
  const uint32_t fmt_size = 16;
  const uint16_t pcm_tag = 1, channels = 1, bits = 16, align = 2;
  const uint32_t byte_rate = rate * 2;
  fwrite("RIFF", 1, 4, f); fwrite(&riff, 4, 1, f); fwrite("WAVE", 1, 4, f);
  fwrite("fmt ", 1, 4, f); fwrite(&fmt_size, 4, 1, f);
  fwrite(&pcm_tag, 2, 1, f); fwrite(&channels, 2, 1, f);
  fwrite(&rate, 4, 1, f); fwrite(&byte_rate, 4, 1, f);
  fwrite(&align, 2, 1, f); fwrite(&bits, 2, 1, f);
  fwrite("data", 1, 4, f); fwrite(&data_bytes, 4, 1, f);
  fwrite(pcm.data(), 2, pcm.size(), f);
  fclose(f);
}

// Centre of a hysteresis-quantizer step, so a word is selected unambiguously
// rather than landing on a boundary the quantizer could resolve either way.
float StepCentre(int index, int count) {
  if (count <= 1) return 0.5f;
  return (static_cast<float>(index) + 0.5f) / static_cast<float>(count);
}

void RenderWord(int bank_index, int word_in_bank, int words_in_bank,
                float prosody_bipolar, size_t frames,
                std::vector<float>* out_samples) {
  // Zero the storage and placement-new on top of it: memset over a CONSTRUCTED
  // object would clobber its vptr. Same reason the arena is cleared first.
  stmlib::Random::Seed(0x21);
  memset(g_ram_block, 0, sizeof(g_ram_block));
  stmlib::BufferAllocator allocator(g_ram_block, sizeof(g_ram_block));

  alignas(plaits::NaturalSpeechEngine) char storage[
      sizeof(plaits::NaturalSpeechEngine)];
  memset(storage, 0, sizeof(storage));
  plaits::NaturalSpeechEngine& e =
      *new (storage) plaits::NaturalSpeechEngine();
  e.Init(&allocator);
  e.Reset();
  e.set_prosody_amount(prosody_bipolar);
  e.set_speed(0.0f);

  // Constructed, not memset: EngineParameters has a constructor that sets
  // frequency_offset and the articulation-envelope fields, and zeroing over it
  // would silently stop doing the right thing if it ever gains a member that
  // needs a non-zero default.
  plaits::EngineParameters p;
  p.note = 48.0f;
  p.accent = 0.8f;
  p.harmonics = StepCentre(bank_index, bank::kNumBanks);
  p.morph = StepCentre(word_in_bank, words_in_bank);
  p.timbre = 0.5f;       // tract as recorded
  p.macro = 0.5f;        // articulation as recorded
  p.chord_set_option = 0;
  p.stereo = false;
  p.trigger = plaits::TRIGGER_HIGH | plaits::TRIGGER_RISING_EDGE;

  float out[kBlock] = {};
  float aux[kBlock] = {};
  out_samples->clear();
  out_samples->reserve(frames);
  for (size_t frame = 0; frame < frames; frame += kBlock) {
    bool already_enveloped = false;
    e.Render(p, out, aux, kBlock, &already_enveloped);
    // The rising edge fires once; holding it would retrigger every block.
    p.trigger = plaits::TRIGGER_HIGH;
    for (size_t i = 0; i < kBlock && out_samples->size() < frames; ++i) {
      out_samples->push_back(out[i] * kOutGain);
    }
  }
}

}  // namespace

int main(int argc, char** argv) {
  if (argc < 2) {
    fprintf(stderr, "usage: %s <output-dir> [seconds-per-word]\n", argv[0]);
    return 2;
  }
  const std::string dir = argv[1];
  const float seconds = argc > 2 ? atof(argv[2]) : 2.0f;
  const size_t frames = static_cast<size_t>(seconds * kSampleRate);

  // Rendered first, scaled second. TRIG is patched for a word preview, so on
  // hardware Voice's LPG shapes the output; this harness bypasses the LPG (as
  // the palette preview renderer does), which leaves peaks above full scale.
  // Clamping would clip, and per-word normalising would flatten the real
  // loudness differences between words -- so every render is scaled by ONE
  // factor derived from the loudest of them.
  std::vector<std::vector<float> > rendered;
  std::vector<std::string> names;
  std::vector<float> concat_natural;
  std::vector<float> concat_flat;
  std::vector<float> buffer;
  int global_word = 0;

  for (int b = 0; b < bank::kNumBanks; ++b) {
    const int first = bank::kBankFirstWord[b];
    const int words = bank::kBankFirstWord[b + 1] - first;
    for (int w = 0; w < words; ++w) {
      char name[128];
      // -1.0 => monotone, 0.0 => the recorded contour. The engine's
      // set_prosody_amount is 1 + bipolar, so these are its 0 and 1.
      const struct { const char* label; float prosody;
                     std::vector<float>* concat; } modes[] = {
        {"natural", 0.0f, &concat_natural},
        {"flat", -1.0f, &concat_flat},
      };
      for (int m = 0; m < 2; ++m) {
        RenderWord(b, w, words, modes[m].prosody, frames, &buffer);
        snprintf(name, sizeof(name), "%s/word-%02d-%s.wav",
                 dir.c_str(), global_word, modes[m].label);
        rendered.push_back(buffer);
        names.push_back(name);
        modes[m].concat->insert(modes[m].concat->end(),
                                buffer.begin(), buffer.end());
      }
      ++global_word;
    }
  }

  float peak = 0.0f;
  for (size_t i = 0; i < rendered.size(); ++i) {
    for (size_t j = 0; j < rendered[i].size(); ++j) {
      const float m = rendered[i][j] < 0.0f ? -rendered[i][j] : rendered[i][j];
      if (m > peak) peak = m;
    }
  }
  // Scaled to the headroom target in BOTH directions. Real speech peaks well
  // below full scale (a measured bank came in at 0.16, i.e. -16 dBFS), which is
  // too quiet to audition next to the rest of the editor; only attenuating
  // would leave it there. One factor for the whole bank, so a word that is
  // genuinely weaker than its neighbours still sounds weaker.
  const float kHeadroom = 0.891f;   // -1 dBFS
  const float scale = peak > 1e-6f ? kHeadroom / peak : 1.0f;
  for (size_t i = 0; i < rendered.size(); ++i) {
    for (size_t j = 0; j < rendered[i].size(); ++j) rendered[i][j] *= scale;
    WriteWav(names[i], rendered[i]);
  }
  for (size_t j = 0; j < concat_natural.size(); ++j) concat_natural[j] *= scale;
  for (size_t j = 0; j < concat_flat.size(); ++j) concat_flat[j] *= scale;
  WriteWav(dir + "/bank-natural.wav", concat_natural);
  WriteWav(dir + "/bank-flat.wav", concat_flat);
  printf("{\"words\": %d, \"banks\": %d, \"peak\": %.4f, \"scale\": %.4f}\n",
         global_word, bank::kNumBanks, peak, scale);
  return 0;
}
