#!/usr/bin/env python3
"""Validate and render recipe-provided Plaits Speech word banks."""

from __future__ import annotations

import base64
import struct
from typing import Any


FRAME_STRUCT = struct.Struct("<BBhh8b")
MAX_STOCK_BANK = 4
MAX_BANKS = 8
MAX_WORDS = 16
MAX_FRAMES = 1024


def validate_speech_banks(value: Any) -> dict[str, Any]:
    if not isinstance(value, dict) or set(value) != {"stockBankIds", "customBanks"}:
        raise ValueError("speechBanks must contain stockBankIds and customBanks")
    stock = value["stockBankIds"]
    custom = value["customBanks"]
    if (not isinstance(stock, list)
            or any(type(bank) is not int or bank < 0 or bank > MAX_STOCK_BANK for bank in stock)
            or len(set(stock)) != len(stock)):
        raise ValueError("speechBanks stockBankIds must be distinct values from 0 through 4")
    if not isinstance(custom, list) or not 1 <= len(stock) + len(custom) <= MAX_BANKS:
        raise ValueError(f"Speech must contain between one and {MAX_BANKS} total banks")

    normalized = []
    for bank in custom:
        if not isinstance(bank, dict) or set(bank) != {"words", "wordBoundaries", "frameData"}:
            raise ValueError("a custom Speech bank has an unsupported shape")
        words = bank["words"]
        boundaries = bank["wordBoundaries"]
        encoded = bank["frameData"]
        if (not isinstance(words, list) or not 1 <= len(words) <= MAX_WORDS
                or any(not isinstance(word, str) or not word.strip() or len(word) > 80 for word in words)):
            raise ValueError(f"a custom Speech bank must contain 1 through {MAX_WORDS} named words")
        if not isinstance(encoded, str):
            raise ValueError("a custom Speech bank is missing its LPC frame data")
        try:
            packed = base64.b64decode(encoded, validate=True)
        except (ValueError, TypeError) as error:
            raise ValueError("a custom Speech bank contains invalid LPC frame data") from error
        if not packed or len(packed) % FRAME_STRUCT.size:
            raise ValueError("a custom Speech bank contains misaligned LPC frame data")
        frame_count = len(packed) // FRAME_STRUCT.size
        if frame_count > MAX_FRAMES:
            raise ValueError(f"a custom Speech bank exceeds {MAX_FRAMES} LPC frames")
        if (not isinstance(boundaries, list) or len(boundaries) != len(words) + 1
                or any(type(item) is not int for item in boundaries)
                or boundaries[0] != 0 or boundaries[-1] != frame_count
                or any(right <= left for left, right in zip(boundaries, boundaries[1:]))):
            raise ValueError("a custom Speech bank contains invalid word boundaries")
        # Unpacking proves every frame has exactly the firmware's packed shape.
        frames = [FRAME_STRUCT.unpack_from(packed, offset)
                  for offset in range(0, len(packed), FRAME_STRUCT.size)]
        normalized.append({
            "words": [word.strip() for word in words],
            "wordBoundaries": boundaries,
            "frameData": base64.b64encode(packed).decode("ascii"),
            "frames": frames,
        })
    return {"stockBankIds": stock, "customBanks": normalized}


def _safe_comment(value: str) -> str:
    return "".join(character if 32 <= ord(character) < 127 else "_" for character in value)


def render_speech_config(value: dict[str, Any] | None) -> str:
    if value is None:
        return """// Generated by speech_banks.py. Do not edit.
#ifndef PLAITS_DSP_SPEECH_RECIPE_CONFIG_H_
#define PLAITS_DSP_SPEECH_RECIPE_CONFIG_H_
#define PLAITS_HAS_CUSTOM_SPEECH_BANKS 0
#endif
"""

    stock = value["stockBankIds"]
    custom = value["customBanks"]
    lines = [
        "// Generated by speech_banks.py. Do not edit.",
        "#ifndef PLAITS_DSP_SPEECH_RECIPE_CONFIG_H_",
        "#define PLAITS_DSP_SPEECH_RECIPE_CONFIG_H_",
        "#define PLAITS_HAS_CUSTOM_SPEECH_BANKS 1",
        f"#define CUSTOM_SPEECH_NUM_STOCK_BANKS {len(stock)}",
        f"#define CUSTOM_SPEECH_NUM_WORD_BANKS {len(custom)}",
        '#include "plaits/dsp/speech/lpc_speech_synth_controller.h"',
        '#include "plaits/dsp/speech/lpc_speech_synth_words.h"',
        "namespace plaits {",
    ]
    if stock:
        lines.append("static const LPCSpeechSynthWordBankData custom_speech_stock_word_banks[] = {")
        lines.extend(f"  {{ bank_{bank}, sizeof(bank_{bank}) }}," for bank in stock)
        lines.append("};")
    else:
        lines.append("static const LPCSpeechSynthWordBankData* const custom_speech_stock_word_banks = NULL;")

    for bank_index, bank in enumerate(custom):
        lines.append(f"// Custom bank {bank_index}")
        lines.append(f"static const LPCSpeechSynth::Frame custom_speech_bank_{bank_index}_frames[] = {{")
        boundaries = bank["wordBoundaries"]
        for word_index, word in enumerate(bank["words"]):
            lines.append(f"  // {word_index}: {_safe_comment(word)}")
            for frame in bank["frames"][boundaries[word_index]:boundaries[word_index + 1]]:
                lines.append("  { " + ", ".join(str(field) for field in frame) + " },")
        lines.append("};")
        lines.append(
            f"static const uint16_t custom_speech_bank_{bank_index}_boundaries[] = {{ "
            + ", ".join(str(item) for item in boundaries) + " };")

    if custom:
        lines.append("static const LPCSpeechSynthRawWordBankData custom_speech_word_banks[] = {")
        for bank_index, bank in enumerate(custom):
            lines.append(
                f"  {{ custom_speech_bank_{bank_index}_frames, "
                f"custom_speech_bank_{bank_index}_boundaries, "
                f"{len(bank['frames'])}, {len(bank['words'])} }},")
        lines.append("};")
    else:
        lines.append("static const LPCSpeechSynthRawWordBankData* const custom_speech_word_banks = NULL;")
    lines.extend(["}  // namespace plaits", "#endif", ""])
    return "\n".join(lines)
