#!/usr/bin/env python3
"""Convert continuous LPC frame plans into a compact C++ include file."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


FIELD_RANGES = (
    (0, 255),
    (0, 255),
    (-32768, 32767),
    (-32768, 32767),
    *((-128, 127),) * 8,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--phrase",
        action="append",
        required=True,
        metavar="LABEL=PLAN",
        help="phrase label and frame-plan path; repeat to build a bank",
    )
    parser.add_argument("--output", required=True, type=Path)
    return parser.parse_args()


def read_phrase(specification: str) -> tuple[str, list[tuple[int, ...]]]:
    if "=" not in specification:
        raise ValueError(f"phrase must be LABEL=PLAN: {specification}")
    label, raw_path = specification.split("=", 1)
    label = label.strip()
    if not label:
        raise ValueError("phrase label cannot be empty")
    path = Path(raw_path)
    frames: list[tuple[int, ...]] = []
    for line_number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if not line.strip():
            continue
        try:
            frame = tuple(int(value) for value in line.split())
        except ValueError as error:
            raise ValueError(f"{path}:{line_number}: non-integer frame field") from error
        if len(frame) != len(FIELD_RANGES):
            raise ValueError(
                f"{path}:{line_number}: expected {len(FIELD_RANGES)} fields, got {len(frame)}"
            )
        for index, (value, limits) in enumerate(zip(frame, FIELD_RANGES)):
            if not limits[0] <= value <= limits[1]:
                raise ValueError(
                    f"{path}:{line_number}: field {index} value {value} outside {limits}"
                )
        frames.append(frame)
    if not frames:
        raise ValueError(f"{path}: no frames")
    return label, frames


def safe_comment(text: str) -> str:
    return re.sub(r"[^A-Za-z0-9 .,;:_?!'()-]", "_", text)


def main() -> int:
    args = parse_args()
    phrases = [read_phrase(specification) for specification in args.phrase]
    if len(phrases) > 65535:
        raise SystemExit("too many phrases")

    offsets: list[int] = []
    lengths: list[int] = []
    cursor = 0
    lines = [
        "// Copyright 2026 Lyle Mills.",
        "// SPDX-License-Identifier: MIT",
        "// Generated by plaits/test/lpc_plan_to_cpp.py. Do not edit by hand.",
        "// Each phrase carries one duplicate guard frame for interpolated reads.",
        "const LPCSpeechSynth::Frame kPhraseFrames[] = {",
    ]
    for index, (label, frames) in enumerate(phrases):
        if cursor > 65535 or len(frames) > 65535:
            raise SystemExit("phrase bank exceeds 16-bit frame offsets")
        offsets.append(cursor)
        lengths.append(len(frames))
        lines.append(f"  // {index}: {safe_comment(label)} ({len(frames)} frames)")
        for frame in frames:
            lines.append("  { " + ", ".join(str(value) for value in frame) + " },")
        lines.append("  { " + ", ".join(str(value) for value in frames[-1]) + " },  // guard")
        cursor += len(frames) + 1
    lines.extend([
        "};",
        "",
        "const uint16_t kPhraseOffsets[] = { "
            + ", ".join(str(value) for value in offsets) + " };",
        "const uint16_t kPhraseLengths[] = { "
            + ", ".join(str(value) for value in lengths) + " };",
        f"const int kNumPhrases = {len(phrases)};",
        "",
    ])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")
    print(
        f"wrote {args.output}: {len(phrases)} phrases, "
        f"{sum(lengths)} frames plus {len(phrases)} guards"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
