#!/usr/bin/env python3
"""Generate the Palette Seed3 engine tables from the Plaits Palette catalog.

Writes, for each engine SET, a header the firmware includes and a CMake
fragment naming the translation units that set needs:

    generated/<set>/engine_table.h
    generated/<set>/sources.cmake

Sets:
    all      every catalog engine (96 at catalog schema 1 / 2026-09)
    stock24  the 24 engines of stock Plaits v1.2 (the BOOT_SRAM comparison)
    va       Virtual Analog alone (the single-engine bring-up app)

Run from anywhere:  python3 tools/gen_engine_table.py [--check]
The outputs are committed; --check fails if they are stale.
"""
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
FW = os.path.dirname(HERE)
REPO = os.path.dirname(os.path.dirname(FW))
CATALOG = os.path.join(REPO, "alt_firmwares/plaits_lab_catalog/catalog.json")

# Shared translation units every set links (the engines' common closure).
SHARED_SOURCES = [
    "plaits/resources.cc",
    "plaits/dsp/chords/chord_bank.cc",
    "plaits/dsp/fm/algorithms.cc",
    "plaits/dsp/fm/dx_units.cc",
    "plaits/dsp/physical_modelling/modal_voice.cc",
    "plaits/dsp/physical_modelling/resonator.cc",
    "plaits/dsp/physical_modelling/string.cc",
    "plaits/dsp/physical_modelling/string_voice.cc",
    "plaits/dsp/speech/lpc_speech_synth.cc",
    "plaits/dsp/speech/lpc_speech_synth_controller.cc",
    "plaits/dsp/speech/lpc_speech_synth_phonemes.cc",
    "plaits/dsp/speech/lpc_speech_synth_words.cc",
    "plaits/dsp/speech/naive_speech_synth.cc",
    "plaits/dsp/speech/sam_speech_synth.cc",
    "plaits/dsp/engine2/scale_voices.cc",
    "plaits/dsp/engine2/scale_wavetable_voices.cc",
    "plaits/dsp/engine2/freshets_formant_shapes.cc",
    "plaits/dsp/engine2/triple_engine_data.cc",
    "plaits/dsp/engine2/vowel_fof_data.cc",
    "stmlib/dsp/atan.cc",
    "stmlib/dsp/units.cc",
    "stmlib/utils/random.cc",
]

# Engines that are inert without built-in user data (see the softsynth's
# core/tools/gen_engine_table.py, which carries the same table): the three
# DX7 banks take a packed patch bank from resources.cc, Wave Terrain takes
# the 64x64 default surface the firmware builds at boot.
USER_DATA = {
    "dx7-bank-a": "kFmBankA",
    "dx7-bank-b": "kFmBankB",
    "dx7-bank-c": "kFmBankC",
    "wave-terrain": "kWaveTerrain",
}

STOCK24_CLASSES = {
    "VirtualAnalogVCFEngine", "PhaseDistortionEngine", "SixOpEngine",
    "WaveTerrainEngine", "StringMachineEngine", "ChiptuneEngine",
    "VirtualAnalogEngine", "WaveshapingEngine", "FMEngine", "GrainEngine",
    "AdditiveEngine", "WavetableEngine", "ChordEngine", "SpeechEngine",
    "SwarmEngine", "NoiseEngine", "ParticleEngine", "StringEngine",
    "ModalEngine", "BassDrumEngine", "SnareDrumEngine", "HiHatEngine",
}

SETS = {
    "all": lambda e: True,
    "stock24": lambda e: e["source"]["className"] in STOCK24_CLASSES,
    "va": lambda e: e["id"] == "virtual-analog",
}


def cident(s):
    return "".join(ch if ch.isalnum() else "_" for ch in s)


def emit(set_name, engines):
    out_dir = os.path.join(FW, "generated", set_name)
    os.makedirs(out_dir, exist_ok=True)
    headers = sorted({e["source"]["header"] for e in engines})
    sources = sorted(set(SHARED_SOURCES) | {
        f for e in engines for f in e["source"].get("files", []) if f.endswith(".cc")})

    h = []
    h.append("// GENERATED by tools/gen_engine_table.py from")
    h.append("// alt_firmwares/plaits_lab_catalog/catalog.json - DO NOT EDIT.")
    h.append(f"// Engine set: {set_name} ({len(engines)} engines).")
    h.append("#ifndef PALETTE_SEED3_ENGINE_TABLE_H_")
    h.append("#define PALETTE_SEED3_ENGINE_TABLE_H_")
    h.append("")
    for hdr in headers:
        h.append(f'#include "{hdr}"')
    h.append("")
    h.append(f"#define PALETTE_ENGINE_SET \"{set_name}\"")
    h.append(f"#define PALETTE_ENGINE_COUNT {len(engines)}")
    h.append("")
    h.append("// X(index, id, name, ClassName, out_gain, aux_gain, already_enveloped, user_data)")
    h.append("#define PALETTE_ENGINES(X) \\")
    for i, e in enumerate(engines):
        pp = e["postProcessing"]
        ud = USER_DATA.get(e["id"], "kNone")
        name = e["name"].replace('"', "'")
        h.append(f'  X({i}, "{e["id"]}", "{name}", plaits::{e["source"]["className"]}, '
                 f'{pp["outGain"]}f, {pp["auxGain"]}f, '
                 f'{"true" if pp["alreadyEnveloped"] else "false"}, {ud}) \\')
    h.append("")
    h.append("#endif  // PALETTE_SEED3_ENGINE_TABLE_H_")
    header_text = "\n".join(h) + "\n"

    c = []
    c.append("# GENERATED by tools/gen_engine_table.py - DO NOT EDIT.")
    c.append(f"# Engine set: {set_name} ({len(engines)} engines, {len(sources)} translation units).")
    c.append(f"set(PALETTE_{set_name.upper()}_SOURCES")
    for s in sources:
        c.append(f"    ${{PALETTE_REPO}}/{s}")
    c.append(")")
    cmake_text = "\n".join(c) + "\n"
    return {
        os.path.join(out_dir, "engine_table.h"): header_text,
        os.path.join(out_dir, "sources.cmake"): cmake_text,
    }


def main():
    check = "--check" in sys.argv
    cat = json.load(open(CATALOG))
    engines = cat["engines"]
    outputs = {}
    for name, pred in SETS.items():
        sel = [e for e in engines if pred(e)]
        outputs.update(emit(name, sel))
        print(f"{name}: {len(sel)} engines", file=sys.stderr)
    stale = []
    for path, text in outputs.items():
        if check:
            cur = open(path).read() if os.path.exists(path) else None
            if cur != text:
                stale.append(path)
        else:
            open(path, "w").write(text)
    if check and stale:
        print("STALE: " + " ".join(os.path.relpath(p, FW) for p in stale), file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
