#!/usr/bin/env python3
"""Derive the Palette Seed3 linker scripts from libDaisy's own.

    python3 tools/make_lds.py        # writes ld/palette_{qspi,qspi_notables,sram}.lds

Three layouts, one app (plan §27 "intended memory layout"):
  qspi           BOOT_QSPI, engine code executes in place from QSPI; ALL
                 plaits/stmlib .rodata (the ~145 KB of tables) rides in .data
                 so the startup copy lands it in AXI SRAM.
  qspi_notables  BOOT_QSPI control: tables stay in QSPI (is the copy needed?).
  sram           BOOT_SRAM comparison: code + tables in AXI SRAM; .bss moved
                 out of DTCM to SRAM so a 24-engine image fits beside it.
All three pin the same hot code into ITCM (.itcm_text, copied before static
constructors by palette_copy_itcm in src/main.cc) and keep the FwVoices in
DTCM, so the variants differ only in where engine code and tables live.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
FW = os.path.dirname(HERE)
CORE = os.path.join(FW, "libDaisy/core")

HEADER = """/* Palette Seed3 linker script, derived from libDaisy core/STM32H750IB_%s.lds
 * (BSD, LinkerScriptGenerator + Electrosmith). GENERATED by tools/make_lds.py.
 * Layout:
 *   .itcm_text   hot shared code -> ITCM (copied at boot by palette_copy_itcm)
 *                = stmlib IN_RAM (.ramtext), stmlib + plaits shared objects,
 *                  the firmware voice/callback, libDaisy's audio/SAI/DMA path
 *   .data        %s
 *   .dtcmram_bss the four FwVoices (DTCM_MEM_SECTION)
 */
"""

PINNED = ("*/stmlib/*.obj */plaits/dsp/envelope.cc.obj */plaits/resources.cc.obj "
          "*/src/fw_voice*.obj */src/main.cc.obj */src/user_data.cc.obj "
          "*libdaisy.a:audio.cpp.obj *libdaisy.a:sai.cpp.obj *libdaisy.a:dma.c.obj")

ITCM = """	.itcm_text :
	{
		. = ALIGN(8);
		_sitcm = .;
		*(.ramtext)
		*(.ramtext*)
%s		. = ALIGN(8);
		_eitcm = .;
	} > ITCMRAM AT > %s
	_siitcm = LOADADDR(.itcm_text);

""" % ("".join("\t\t%s(.text .text*)\n" % p for p in PINNED.split()), "%s")

TABLES = "*/plaits/*.obj */stmlib/*.obj"


def patch(s, region, tables_to_data):
    # The ITCM copy routine must NOT be pinned (it runs before the copy).
    s = s.replace("\t\t*(.text)\n\t\t*(.text*)\n",
                  "\t\t*(.qspi_startup)\n\t\t*(EXCLUDE_FILE(%s) .text)\n\t\t*(EXCLUDE_FILE(%s) .text*)\n"
                  % (PINNED, PINNED), 1)
    if tables_to_data:
        s = s.replace("\t\t*(.rodata)\n\t\t*(.rodata*)\n",
                      "\t\t*(EXCLUDE_FILE(%s) .rodata)\n\t\t*(EXCLUDE_FILE(%s) .rodata*)\n"
                      % (TABLES, TABLES), 1)
    marker = "\t} > %s\n\n\t.text :" % region
    assert marker in s, region
    return s.replace(marker, "\t} > %s\n\n" % region + ITCM % region + "\t.text :", 1)


def main():
    qspi = open(os.path.join(CORE, "STM32H750IB_qspi.lds")).read()
    sram = open(os.path.join(CORE, "STM32H750IB_sram.lds")).read()
    out = {}

    q = patch(qspi, "QSPIFLASH", True)
    q = q.replace("\t\t*(.data)\n\t\t*(.data*)\n",
                  "\t\t*(.data)\n\t\t*(.data*)\n"
                  "\t\t/* constant tables, copied to AXI SRAM by the startup .data copy */\n"
                  "\t\t*/plaits/*.obj(.rodata .rodata*)\n\t\t*/stmlib/*.obj(.rodata .rodata*)\n", 1)
    out["palette_qspi.lds"] = HEADER % (
        "qspi", "libDaisy data + ALL plaits/stmlib .rodata (tables) -> AXI SRAM, LMA in QSPI") + q

    out["palette_qspi_notables.lds"] = HEADER % (
        "qspi", "libDaisy data only -> AXI SRAM; plaits tables stay in QSPI (control build)") \
        + patch(qspi, "QSPIFLASH", False)

    r = patch(sram, "SRAM", False)
    old = ("\t\t*(COMMON)\n\t\t. = ALIGN(4);\n\t\t_ebss = .;\n\n\t\tPROVIDE(__bss_end__ = _ebss);\n\t} > DTCMRAM")
    assert old in r
    r = r.replace(old, old[:-len("DTCMRAM")] + "SRAM", 1)
    out["palette_sram.lds"] = HEADER % (
        "sram", "libDaisy + plaits .data -> DTCM (LMA in SRAM); .bss -> AXI SRAM after the code") + r

    os.makedirs(os.path.join(FW, "ld"), exist_ok=True)
    for name, text in out.items():
        open(os.path.join(FW, "ld", name), "w").write(text)
        print("wrote ld/" + name)


if __name__ == "__main__":
    main()
